2:
  cross: ["", 3, 5, 1]
  tag_id: [132, "", 152, 142]

3:
  cross: ["", "", 4, 2]
  tag_id: [133, "", 153, 143]


4:
  cross: [3, "", "", 5]
  tag_id: [154, 144, 134, '']

5:
  cross: [2, 4, "", ""]
  tag_id: ["", 155, 145, 135]