  cross: [2, 200, 4, ""]
  tag_id: ["", 152, 142, 132]
2:
  cross: ["", 3, 100, 1]
  tag_id: [133, "", 153, 143]


  3:
    cross:
      - 2
      - 5
      - 4
      - ""
    tag_id:
      - ""
      - 154
      - 144
      - 134

  4:
    cross:
      - ""
      - 3
      - 10
      - 1
    tag_id:
      - 135
      - ""
      - 155
      - 145

  5:
    cross:
      - 6
      - ""
      - 9
      - 3
    tag_id:
      - 146
      - 136
      - ""
      - 156

  6:
    cross:
      - ""
      - 7
      - 8
      - 5
    tag_id:
      - 137
      - ""
      - 157
      - 147

  7:
    cross:
      - 6
      - ""
      - 9
      - 8
    tag_id:
      - 148
      - 138
      - ""
      - 158

  8:
    cross:
      - 6
      - 7
      - 9
      - ""
    tag_id:
      - ""
      - 159
      - 149
      - 139

  9:
    cross:
      - 8
      - 7
      - ""
      - 5
    tag_id:
      - 160
      - 150
      - 140
      - ""

  10:
    cross:
      - 4
      - 11
      - ""
      - 14
    tag_id:
      - 161
      - 151
      - 141
      - ""

  11:
    cross:
      - 10
      - ""
      - 12
      - 13
    tag_id:
      - 236
      - 235
      - ""
      - 137

  12:
    cross:
      - 13
      - 11
      - ""
      - 14
    tag_id:
      - 240
      - 239
      - 238
      - ""

  13:
    cross:
      - ""
      - 11
      - 12
      - 14
    tag_id:
      - 241
      - ""
      - 242
      - 243

  14:
    cross:
      - 10
      - 13
      - 12
      - ""
    tag_id:
      - ""
      - 245
      - 246
      - 244

