6:
  cross: 
    - ""
    - 7
    - 8
    - 9
  tag_id:
    - 137
    - ""
    - 157
    - 147

7:
  cross: 
    - 6
    - ""
    - 9
    - 8
  tag_id:
    - 148
    - 138
    - ""
    - 158

8:
  cross: 
    - 6
    - 7
    - 9
    - ""
  tag_id:
    - ""
    - 159
    - 149 
    - 139

9:
  cross: 
    - 8
    - 7
    - ""
    - 6
  tag_id:
    - 160
    - 150
    - 140
    - ""